name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker image
        continue-on-error: true
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} || echo "Build finished (log streaming failed)"


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --set-env-vars VITE_ENV=production,VITE_API_URL="${{ secrets.VITE_API_URL }}",VITE_API_KEY="${{ secrets.VITE_API_KEY }}",VITE_AUTH_DOMAIN="${{ secrets.VITE_AUTH_DOMAIN }}",VITE_PROJECT_ID="${{ secrets.VITE_PROJECT_ID }}",VITE_STORAGE_BUCKET="${{ secrets.VITE_STORAGE_BUCKET }}",VITE_APP_ID="${{ secrets.VITE_APP_ID }}",VITE_MEASUREMENT_ID="${{ secrets.VITE_MEASUREMENT_ID }}",VITE_MESSAGING_SENDER_ID="${{ secrets.VITE_MESSAGING_SENDER_ID }}"
